### ISSUE TITLE
Object has no attribute 'foregrounds_dir'

### ISSUE THREAD

**Issue by HenriqueLeal** [akTwelve/cocosynth#19]
Hi, congratulations on your work, today I tried to create images using 'image_composition.py', I create the same directory tree that you recommend, but when I start image_composition.py the errors occur:

python3 ./python/image_composition.py --input_dir ./datasets/challenge_dataset/input --output_dir ./datasets/challenge_dataset/output --count 10 --width 480 --height 360
Traceback (most recent call last):
  File "./python/image_composition.py", line 484, in <module>
    image_comp.main(args)
  File "./python/image_composition.py", line 458, in main
    self._validate_and_process_args(args)
  File "./python/image_composition.py", line 148, in _validate_and_process_args
    self._validate_and_process_input_directory()
  File "./python/image_composition.py", line 179, in _validate_and_process_input_directory
    assert self.foregrounds_dir is not None, 'foregrounds sub-directory was not found in the input_dir'
AttributeError: 'ImageComposition' object has no attribute 'foregrounds_dir'

Thank you!!

**Comment by HenriqueLeal** [comment]
I'm sorry, I create "background" and "foreground" not "backgrounds" and "foregrounds"
